version: 2
jobs:
    build:
        working_directory: ~/Django_Airbnb_Clone
        docker:
            - image: circleci/python:3.7
        steps:
            - checkout
            - run: sudo chown -R circleci:circleci /usr/local/bin
            - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
            - restore_cache:
                  key: deps10-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
            - run:
                  command: |
                      echo "--- Start Install Pipenv ---"
                      sudo pip install pipenv
                      echo "--- Start Install Pipenv dependencies ---"
                      pipenv install
                      pipenv graph
            - save_cache:
                  key: deps10-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
                  paths:
                      - '.venv'
                      - '/usr/local/bin'
                      - '/usr/local/lib/python3.6/site-packages'
            - run:
                  command: |
                      echo "--- Start Pipenv Virtual Env ---"
                      pipenv run
                      echo "--- Start Test Using Coverage ---"
                      coverage manage.py test
                      echo "--- Start Save Using Codecov ---"
                      codecov
